# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: stacksoumik
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mr-projectd
# "service" is the name of this project. This will also be added to your AWS resource names.
service: mr-project

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1

functions:
  api:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
