export const NotificationTypes = {
  Review: 'Review',
  paymentConfirmation: 'paymentConfirmation',
  Order: 'Order',
  OrderStart: 'OrderStart',
  Instructions: 'Instructions',
  Reminder: 'Reminder',
  OrderMessage: 'OrderMessage',
  Message: 'Message',
  Revision: 'Revision',
  Comment: 'Comment',
  OrderExtend: 'OrderExtend',
  OrderExtendAccept: 'OrderExtendAccept',
  OrderExtendReject: 'OrderExtendReject',
  OrderExtendWithdraw: 'OrderExtendWithdraw',
  OrderExtendUser: 'OrderExtendUser',
  OrderExtendAdmin: 'OrderExtendAdmin',
  AdditionalOffer: 'AdditionalOffer',
  AdditionalOfferAccept: 'AdditionalOfferAccept',
  AdditionalOfferWithdraw: 'AdditionalOfferWithdraw',
  CancelAccept: 'CancelAccept',
  CancelAcceptUser: 'CancelAcceptUser',
  DirectCancel: 'DirectCancel',
  AttchFile: 'AttchFile',
  FileDelivered: 'FileDelivered',
  RevisionDateUpdated: 'RevisionDateUpdated',
  Feedback: 'Feedback',
  CompleteOrder: 'CompleteOrder',
  CompleteOrderUser: 'CompleteOrderUser',
  AutoCompleteOrder: 'AutoCompleteOrder',
  AutoCancelOrder: 'AutoCancelOrder',
  AutoCompleteOrderUser: 'AutoCompleteOrder',
  Tips: 'Tips',
  AffiliateWidthrawRequsted: 'AffiliateWidthrawRequsted',
  CustomOfferByClient: 'CustomOfferByClient',
  OfferReject: 'OfferReject',
  CancelOffer: 'CancelOffer',
  CancelOfferReject: 'CancelOfferReject',
  CancelOfferWithdraw: 'CancelOfferWithdraw',
  OrderAttchFile: 'OrderAttchFile',
  
};

export type NotificationType =
  (typeof NotificationTypes)[keyof typeof NotificationTypes];
