export enum OrderStatus {
    PROJECT_PLACED = "PROJECT_PLACED",
    REQUIREMENTS_SUBMITTED = "REQUIREMENTS_SUBMITTED",
    PROJECT_RUNNING = "PROJECT_RUNNING",
    REVIEW_DELIVERY = "REVIEW_DELIVERY",
    COMPLETE_PROJECT = "COMPLETE_PROJECT"
}

