import { z } from 'zod';

const subCategorySchema = z.object({
    id: z.string().optional(), // Optional because it will be generated by the database
    subTitle: z.string().min(1, "Subtitle is required"),
    subAmount: z.string().min(0, "Sub amount must be a non-negative integer"),
    regularDeliveryDays: z.string().min(0, "Regular delivery days must be a non-negative integer"),
    fastDeliveryDays: z.string().min(0, "Fast delivery days must be a non-negative integer"),
    fastDeliveryPrice: z.string().min(0, "Fast delivery price must be a non-negative integer"),
    categoryId: z.string().min(1, "Category ID is required").optional(), // Optional if not assigning immediately
});


const categorySchema = z.object({
    id: z.string().optional(), // Optional because it will be generated by the database
    categoryName: z.string().min(1, "Category name is required"),
    image: z.object({
        name: z.string().min(1, "Image name is required"),
        url: z.string().url("Image URL must be valid")
    }).optional(), // Optional if the image is not provided
    bulletPoint: z.array(z.string()).optional(),
    requirements: z.array(z.string()).optional(),
    subCategory: z.array(subCategorySchema).optional(), // Optional if not assigning immediately
});

export { categorySchema, subCategorySchema }